const users = [
  {
    utiId: 1,
    utiPrenom: "John",
    utiNom: "Doe",
    utiPseudo: "johndoe123",
    utiMdp: "password123",
    utiAdmin: false,
    utiPoints: 100,
  },
  {
    utiId: 2,
    utiPrenom: "Jane",
    utiNom: "Smith",
    utiPseudo: "janesmith456",
    utiMdp: "password456",
    utiAdmin: true,
    utiPoints: 200,
  },
  {
    utiId: 3,
    utiPrenom: "Alice",
    utiNom: "Johnson",
    utiPseudo: "alicejohnson789",
    utiMdp: "password789",
    utiAdmin: false,
    utiPoints: 150,
  },
  {
    utiId: 4,
    utiPrenom: "Robert",
    utiNom: "Brown",
    utiPseudo: "robertbrown101",
    utiMdp: "password101",
    utiAdmin: true,
    utiPoints: 250,
  },
  {
    utiId: 5,
    utiPrenom: "Emily",
    utiNom: "Davis",
    utiPseudo: "emilydavis102",
    utiMdp: "password102",
    utiAdmin: false,
    utiPoints: 180,
  },
  {
    utiId: 6,
    utiPrenom: "Michael",
    utiNom: "Miller",
    utiPseudo: "michaelmiller103",
    utiMdp: "password103",
    utiAdmin: true,
    utiPoints: 300,
  },
  {
    utiId: 7,
    utiPrenom: "Sarah",
    utiNom: "Wilson",
    utiPseudo: "sarahwilson104",
    utiMdp: "password104",
    utiAdmin: false,
    utiPoints: 120,
  },
  {
    utiId: 8,
    utiPrenom: "David",
    utiNom: "Moore",
    utiPseudo: "davidmoore105",
    utiMdp: "password105",
    utiAdmin: true,
    utiPoints: 270,
  },
  {
    utiId: 9,
    utiPrenom: "Laura",
    utiNom: "Taylor",
    utiPseudo: "laurataylor106",
    utiMdp: "password106",
    utiAdmin: false,
    utiPoints: 160,
  },
  {
    utiId: 10,
    utiPrenom: "James",
    utiNom: "Anderson",
    utiPseudo: "jamesanderson107",
    utiMdp: "password107",
    utiAdmin: true,
    utiPoints: 220,
  },
];

export { users };
