const users = [
  {
    utiId: 1,
    utiPrenom: "Jean",
    utiNom: "Dupont",
    utiAdresse_Mail: "jean.dupont@example.com",
    utiPseudo: "jdupont",
    utiMdp: "securepassword123",
    utiAdmin: true,
    utiLogged: false,
    utiPoints: 100,
    utiLogCode: 44568,
  },
  {
    utiId: 2,
    utiPrenom: "Marie",
    utiNom: "Curie",
    utiAdresse_Mail: "marie.curie@example.com",
    utiPseudo: "mcurie",
    utiMdp: "securepassword456",
    utiAdmin: false,
    utiLogged: true,
    utiPoints: 200,
    utiLogCode: 44568,
  },
  {
    utiId: 3,
    utiPrenom: "Albert",
    utiNom: "Einstein",
    utiAdresse_Mail: "albert.einstein@example.com",
    utiPseudo: "aeinstein",
    utiMdp: "securepassword789",
    utiAdmin: false,
    utiLogged: false,
    utiPoints: 300,
    utiLogCode: 44568,
  },
  {
    utiId: 4,
    utiPrenom: "Isaac",
    utiNom: "Newton",
    utiAdresse_Mail: "isaac.newton@example.com",
    utiPseudo: "inewton",
    utiMdp: "securepassword012",
    utiAdmin: true,
    utiLogged: true,
    utiPoints: 400,
    utiLogCode: 44568,
  },
  {
    utiId: 5,
    utiPrenom: "Rosalind",
    utiNom: "Franklin",
    utiAdresse_Mail: "rosalind.franklin@example.com",
    utiPseudo: "rfranklin",
    utiMdp: "securepassword345",
    utiAdmin: false,
    utiLogged: true,
    utiPoints: 500,
    utiLogCode: 44568,
  },
];

export { users };
